= https://isaqb.org[iSAQB] Advanced Level Curriculum Formal Methods FM

:toc:
:toc-placement!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Status
image:https://github.com/isaqb-org/curriculum-fm/workflows/CI%20-%20Releases%20and%20Main/badge.svg?branch=main["CI – Releases and Main"]
image:https://img.shields.io/github/last-commit/isaqb-org/curriculum-fm/main.svg["Last commit"]
image:https://img.shields.io/github/contributors/isaqb-org/curriculum-fm.svg["Contributors",link="https://github.com/isaqb-org/curriculum-fm/graphs/contributors"]
image:https://img.shields.io/github/issues/isaqb-org/curriculum-fm.svg["Issues",link="https://github.com/isaqb-org/curriculum-fm/issues"]
image:https://img.shields.io/github/issues-closed/isaqb-org/curriculum-fm.svg["Issues closed",link="https://github.com/isaqb-org/curriculum-fm/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+"]


This is <<copyrighted,copyrighted work>>.

== Content
This repository contains the curriculum Formal Methods.  It is still
in the early stages of development.

toc::[]

== How to contribute or participate
Note that initial development happens on the [dev branch](https://github.com/isaqb-org/curriculum-fm/tree/dev).

Create an issue, a merge- or pull-request

Clone the repository - including the submodule:
+
--
[source,shell]
----
Via SSH:
git clone git@github.com:isaqb-org/curriculum-fm.git --recursive

Via HTTPS:
git clone https://github.com/isaqb-org/curriculum-fm.git --recursive
----
--
. Build the project with http://www.gradle.com[gradle] (you need a locally installed JDK 17 or higher) via `./gradlew`.
. Once the "BUILD SUCCESSFUL" is show, you can review the build result under `./build/`

That will produce both pdf and html output in German (DE) _and_ English (EN), unless you modify the configuration.

== Maintainers

This repository is currently maintained by Mike Sperber and his team.
It was forked from https://github.com/isaqb-org/advanced-template,
so the contributors of that project basically contributed to this one, too.


[[copyrighted]]
== Licensing and Copyright

include::license-copyright/LICENSE.adoc[]
