=== {learning-goals}

// tag::DE[]
[[LZ-4-1]]
==== LZ 4-1: Dies ist das erste Lernziel in Kapitel 4, das mit xyz

Hier wird beschrieben, was Teilnehmer:innen in diesem Lernziel lernen sollen. Das kann in Prosa-Text
in ganzen Sätzen oder in Aufzählungen mit Unterpunkten erfolgen. Dabei kann auch unterschieden werden,
wie wichtig einzelne Aspekte des Lernziels sind. Es kann hier bereits auf Literatur verwiesen werden.

* Erstes Teilziel
* Zweites Unterthema
* Dritter Aspekt

[[LZ-4-2]]
==== LZ 4-2: Hier ist ein zweites Lernziel in diesem Kapitel
tbd.

// end::DE[]

// tag::EN[]
[[LG-4-1]]
==== LG 4-1: Property-Based Testing

Architects understand the concept of property-based testing, can
identify for which properties it is amenable, and guide the
implementation of property-based testing in a software project.


[[LG-4-2]]
==== LG 4-2: Type Systems

Architects understand that type systems can express and ensure properties of
software system.  They are aware of the expressive power of different
type systems, and are familiar with the concept of dependent types.
They can choose languages and tools to exploit the capabilities of a
type system in a software system.

[[LG-4-3]]
==== LG 4-3: Model Checking
tbd.

[[LG-4-4]]
==== LG 4-4: Proof Assistants

Architects understand the mode of operation of proof assistants.  They
are familar with at least one proof assistants.  Architects understand
how to structure a software system to make it amenable to the use of
proof assistants.  They further understand understand how they can
translate requirements on a software projects into proof obligations
for a proof assistant.

[[LG-4-5]]
==== LG 4-5: SMT Solvers
tbd.

[[LG-4-6]]
==== LG 4-6: Abstract Interpretation
tbd.
// end::EN[]

[NOTE]
====
Die einzelnen Lernziele müssen nicht als einfache Aufzählungen mit Unterpunkten aufgeführt werden, sondern können auch gerne in ganzen Sätzen formuliert werden, welche die einzelnen Punkte (sofern möglich) integrieren.
====
