// header file for curriculum section "References"
// (c) iSAQB e.V. (https://isaqb.org)
// ===============================================

[bibliography]
== {references}

**A**

- [[[Aniculaesei,Aniculaesei et al. 2021]]] Aniculaesei Adina, Vorwald, Andreas, Zhang, Meng, and Rausch, Andreas.
  Architecture-based hybrid approach to verify safety-critical automotive system functions by combining data-driven and formal methods. 
  In Cyrille Artho and Rudolf Ramler, editors, 
  2021 IEEE International Conference on Software Architecture Companion (ICSA-C), pages 139–148. IEEE, 2021.

- [[[Aniculaesei,Aniculaesei et al. 2018]]] Aniculaesei Adina, Howar, Falk, Denecke, Peer, and Rausch Andreas.
  Automated generation of requirements-based test cases for an
  adaptive cruise control system.
  In Cyrille Artho and Rudolf Ramler, editors, 
  2018 IEEE Workshop on Validation, Analysis and Evolution of Software Tests (VST@SANER), pages 11–15. IEEE, 2018

**B**

- [[[ball2000,Ball 2000]]] Ball Thomas and Rajamani Sriram:
  Checking Temporal Properties of Software with Boolean Programs,
  Workshop on Advances in Verification, 2000.

**C**

- [[[clarke2018,Clarke et al. 2018]]] Clarke, Edmund M., Henzinger, Thomas A, and Veith, Helmut. 
  Introduction to model checking.
  In Edmund M. Clarke, Thomas A. Henzinger, Helmut Veith, and Roderick Bloem, editors,
  Handbook of Model Checking, pages 1–26. Springer International Publishing, Cham, 2018.

**K**

- [[[klein2009, Klein et al. 2009]]] Klein, Gerwin, Elphinstone,
  Kevin, Heiser, Gernot, Andronick, June, Cock, David, Derrin, Philip,
  Elkaduwe, Dhammika, Engelhardt, Kai, Kolanski, Rafal, Norrish,
  Michael, Sewell, Thomas, Tuch, Harvey and Winwood, Simon.
  seL4: formal verification of an OS kernel.
  SOSP '09: Proceedings of the ACM SIGOPS 22nd symposium on Operating systems principles. October 2009, pages 207–220.

**L**

- [[[leroy2009,Leroy 2009]]] Xavier Leroy: Formal verification of a
  realistic compiler,
  Communications of the ACM 52(7) 2009, pages 107--115.

**N**

- [[[nipkow2018,Nipkow 2022]]] Nipkow, Tobias, editor.
  Isabelle/HOL: A Proof Assistant for Higher-Order Logic,
  volume 2283 of Springer eBook Collection Computer Science. Springer-Verlag Berlin Heidelberg, Berlin, Heidelberg, 2002.
